
parameters:
    lmh_msisdn.format_configuration_service.class:  Lmh\Bundle\MsisdnBundle\Service\MsisdnFormatConfigurationService
    lmh_msisdn.msisdn_validator.class:              Lmh\Bundle\MsisdnBundle\Service\MsisdnValidator
    lmh_msisdn.msisdn_factory.class:                Lmh\Bundle\MsisdnBundle\Service\MsisdnFactory


services:

    lmh_msisdn.format_configuration_service:
        class: "%lmh_msisdn.format_configuration_service.class%"
        arguments: [ "%lmh_msisdn.formats_filename%" ]

    lmh_msisdn.validator:
        class: "%lmh_msisdn.msisdn_validator.class%"
        arguments: [ @lmh_msisdn.format_configuration_service, @lmh_msisdn.msisdn_factory ]
        tags:
            - { name: validator.constraint_validator, alias: msisdn_validator }

    lmh_msisdn.msisdn_factory:
        class: "%lmh_msisdn.msisdn_factory.class%"
        arguments: [ @lmh_msisdn.format_configuration_service, @validator ]
